// swift-tools-version: 6.3

import PackageDescription

let package = Package(
    name: "RoutinaModules",
    platforms: [
        .iOS("26.4"),
        .macOS("26.4"),
    ],
    products: [
        .library(
            name: "RoutinaAppSupport",
            targets: ["RoutinaAppSupport"]
        ),
        .library(
            name: "RoutinaMacSupport",
            targets: ["RoutinaMacSupport"]
        ),
        .executable(
            name: "RoutinaAIMVPCLI",
            targets: ["RoutinaAIMVPCLI"]
        ),
        .executable(
            name: "RoutinaAIMCPServer",
            targets: ["RoutinaAIMCPServer"]
        ),
        .executable(
            name: "RoutinaBackupAudit",
            targets: ["RoutinaBackupAudit"]
        ),
    ],
    dependencies: [
        .package(
            url: "https://github.com/pointfreeco/swift-composable-architecture",
            from: "1.26.2"
        ),
        .package(
            url: "https://github.com/pointfreeco/swift-dependencies",
            from: "1.17.1"
        ),
        .package(
            url: "https://github.com/pointfreeco/swift-case-paths",
            from: "1.9.3"
        ),
        .package(
            url: "https://github.com/pointfreeco/swift-concurrency-extras",
            from: "1.4.1"
        ),
    ],
    targets: [
        .target(
            name: "RoutinaAppSupport",
            dependencies: [
                .product(name: "ComposableArchitecture", package: "swift-composable-architecture"),
                .product(name: "Dependencies", package: "swift-dependencies"),
                .product(name: "CasePaths", package: "swift-case-paths"),
                .product(name: "ConcurrencyExtras", package: "swift-concurrency-extras"),
            ],
            path: "SharedCore",
            exclude: [
                // Files that live in SharedCore but cannot yet be compiled as
                // part of the RoutinaAppSupport package target. Each needs a
                // dedicated migration step before it can move in.
                //
                // Blocked on AppFeature (top-level TCA reducer still lives in
                // the per-app Xcode targets):
                "App/RoutinaAppBootstrap.swift",
                "App/RoutinaAppSceneBootstrap.swift",
                // TODO(styling-injection): These reference TaskDetailPlatformStyle,
                // a per-app enum of UI constants (fonts/colors/padding). The two
                // per-app copies share an API but no implementation, so a naive
                // `#if canImport(UIKit/AppKit)` merge is copy-paste dressed up as
                // sharing and inverts layering (SharedCore picking platform UI
                // tokens). Design a proper injection path — e.g. a
                // `TaskDetailStyling` protocol with per-app conforming values
                // injected via TCA dependency or SwiftUI environment — then move
                // these files in and drop the per-app TaskDetailPlatformStyle.swift
                // copies under iOS/ and RoutinaMacApp/.
                "Screens/TaskDetail/TaskDetailPresentation.swift",
                "Screens/TaskDetail/Graph/RelationshipGraphNodeCard.swift",
                // Blocked on per-app view modifiers (routinaInlineTitleDisplayMode,
                // routinaGraphSheetFrame) plus TaskDetailPlatformStyle above:
                "Screens/TaskDetail/Graph/TaskRelationshipGraphSheet.swift",
                // Not yet audited:
                "Screens/TaskDetail/TaskDetailHeaderViews.swift",
                "Screens/TaskDetail/TaskDetailTaskLadderValuesBox.swift",
                "Screens/TaskDetail/TaskDetailRoutineLogRowContent.swift",
                "Screens/TaskDetail/TaskDetailRoutineLogRowPresentation.swift",
                "Screens/TaskDetail/TaskDetailStatusActionSectionView.swift",
                "Screens/TaskDetail/TaskDetailExtrasSectionView.swift",
                "Screens/TaskDetail/TaskDetailLinkedEventsSectionView.swift",
                "Screens/TaskDetail/TaskDetailPauseUntilSheet.swift",
                "Screens/Home/TaskPlanningDatePickerSheet.swift",
                "Screens/Shared/TaskFormDurationEntry.swift",
                "Screens/Shared/TaskFormLinkedEventsContent.swift",
                "Screens/Shared/TaskFormLinksEditor.swift",
                "Screens/Shared/TaskFormPlaceSelectionMenu.swift",
                "Screens/Shared/TaskTemporalWeightRuleEditor.swift",
                "Screens/Settings/SettingsTagPresentationViews.swift",
                "Features/Settings/SettingsInfoRow.swift",
                "Features/Settings/SettingsSectionGlyphView.swift",
                "Help",
                "Views/RoutineTagPill.swift",
                "Views/AdvancedRecurrenceEditor.swift",
                "Views/SettingsTimelineRowPreviewView.swift",
                "Views/StatsFocus2048Section.swift",
                "Views/StatsHourlyActivitySection.swift",
                "Views/StatsGitHubChartView.swift",
                "Views/StatsGitHubSummaryViews.swift",
                // Shared by the app targets, but these views still rely on
                // platform-owned types or modifiers unavailable to this target.
                "Views/EmojiPickerSheet.swift",
                "Views/PlaceLocationPickerSheet.swift",
                // Extends the per-app HomeTCAView type and is compiled by both
                // Xcode app targets through the shared source folder.
                "Screens/Home/HomeTCAView+ViewState.swift",
                "Screens/Home/HomeTCAView+Refresh.swift",
                "Screens/Home/HomeTCAView+Sorting.swift",
                // Extends the per-app AddRoutineTCAView type.
                "Screens/AddRoutine/AddRoutineTCAView+Bindings.swift",
                "Screens/AddRoutine/AddRoutineTCAView+Presentation.swift",
                "Screens/AddRoutine/AddRoutineTCAView+Composers.swift",
                "Screens/AddRoutine/AddRoutineTCAView+MediaAndRepeat.swift",
            ],
            sources: [
                "App/AppEnvironment.swift",
                "App/RoutinaAppIntents.swift",
                "App/RoutinaScreenshotDataSeeder.swift",
                "App/RoutinaUITestSeeder.swift",
                "AI",
                "Models",
                "Dependencies/AppIconClient.swift",
                "Dependencies/CreationDraftClient.swift",
                "Dependencies/DeviceAuthenticationClient.swift",
                "Dependencies/DependencyValues+.swift",
                "Dependencies/LocationClient.swift",
                "Dependencies/NotificationClient.swift",
                "Dependencies/PlatformSupport.swift",
                "Dependencies/PlatformSupportBase.swift",
                "Dependencies/RoutinaLogClient.swift",
                "Dependencies/UserDefaultsProtocol.swift",
                "Domain/EmojiCatalog.swift",
                "Domain/BlockingWebsiteDomain.swift",
                "Domain/FocusAchievementStats.swift",
                "Domain/FocusActivityIntervals.swift",
                "Domain/FocusDurationStats.swift",
                "Domain/FocusTimerActivityAttributes.swift",
                "Domain/FocusTimerWidgetData.swift",
                "Domain/NotificationPreferences.swift",
                "Domain/PersonalRecordAchievementStats.swift",
                "Domain/PlaceDeduplicationKey.swift",
                "Domain/ProtectionBlockingMode.swift",
                "Domain/StatsAchievementCelebrationStats.swift",
                "Domain/RoutineCompletionStats.swift",
                "Domain/RoutinaDeepLink.swift",
                "Domain/WidgetStats.swift",
                "Domain/RoutineAssumedCompletion.swift",
                "Domain/RoutineDateMath.swift",
                "Domain/RoutineListFilter.swift",
                "Domain/RoutineListSectioningMode.swift",
                "Domain/RoutineLogHistory.swift",
                "Domain/RoutineLogHistory+Advance.swift",
                "Domain/RoutineLogHistory+AssumedCompletion.swift",
                "Domain/RoutineLogHistory+Checklist.swift",
                "Domain/RoutineLogHistory+Fulfillment.swift",
                "Domain/RoutineLogHistory+OccurrenceResolution.swift",
                "Domain/RoutineLogHistory+Removal.swift",
                "Domain/RoutineOccurrenceIdentity.swift",
                "Domain/RoutineVoiceNote.swift",
                "Domain/RoutinaQuickAddParser.swift",
                "Domain/RoutineTag.swift",
                "Domain/FastFilterTags.swift",
                "Domain/GitHubStatsModels.swift",
                "Domain/GitHubWidgetData.swift",
                "Domain/GitLabWidgetData.swift",
                "Domain/SprintBoardModels.swift",
                "Domain/TagCounterDisplayMode.swift",
                "Domain/TagCounterFormatting.swift",
                "Domain/Tab.swift",
                "Domain/TabFilterStateManager.swift",
                "Domain/TemporaryViewState.swift",
                "Domain/TaskImageProcessor.swift",
                "Domain/TaskDestinationSupport.swift",
                "Domain/TimelineLogic.swift",
                "Domain/TodoStateTiming.swift",
                "Dependencies/RoutineDataTransferClient.swift",
                "Features/Timeline/TimelineFeature.swift",
                "Features/Timeline/TimelineFilterPresentation.swift",
                "Features/Timeline/TimelineSelectionSupport.swift",
                "Features/AddRoutine/AddRoutineFeature.swift",
                "Features/AddRoutine/AddRoutineBasicsSupport.swift",
                "Features/AddRoutine/AddRoutineChecklistSupport.swift",
                "Features/AddRoutine/AddRoutineFormSupport.swift",
                "Features/AddRoutine/AddRoutineImageImportSupport.swift",
                "Features/AddRoutine/AddRoutineOrganizationSupport.swift",
                "Features/AddRoutine/AddRoutineOrganizationMutationHandler.swift",
                "Features/AddRoutine/AddRoutineScheduleSupport.swift",
                "Features/AddRoutine/AddRoutineScheduleMutationHandler.swift",
                "Features/AddRoutine/AddRoutineSaveSupport.swift",
                "Features/AddRoutine/AddRoutineFeatureState.swift",
                "Features/AddRoutine/AddRoutineValidationSupport.swift",
                "Features/AddRoutine/AddRoutineViewModifiers.swift",
                "Features/AddRoutine/TaskFormDurationEntryPresentation.swift",
                "Features/AddRoutine/TaskFormPresentation.swift",
                "Features/CreationDrafts/CreationDraftSnapshots.swift",
                "Features/Goals/GoalsFeature.swift",
                "Features/MissingData/MissingTaskMetadataFeature.swift",
                "Features/MissingData/MissingPressureDataFeature.swift",
                "Features/MissingData/MissingPressureDataTaskPresentation.swift",
                "Features/TaskChoice/TaskChoiceFeature.swift",
                "Features/Home/AppFeatureTemporaryViewStateSupport.swift",
                "Features/Home/HomeBoardMutationSupport.swift",
                "Features/Home/HomeFeatureAddRoutineActionHandler.swift",
                "Features/Home/HomeAddRoutineSupport.swift",
                "Features/Home/HomeAdvancedQueryInputSupport.swift",
                "Features/Home/HomeAdvancedQuerySuggestionSelectionSupport.swift",
                "Features/Home/HomeFeatureAddRoutinePresentationRouter.swift",
                "Features/Home/HomeDeduplicationSupport.swift",
                "Features/Home/HomeDetailSelectionSupport.swift",
                "Features/Home/HomeDisplayFilterSupport.swift",
                "Features/Home/HomeFlagFilterSupport.swift",
                "Features/Home/HomeFeatureFilterMutationHandler.swift",
                "Features/Home/HomeFeatureLifecycleActionHandler.swift",
                "Features/Home/HomeFeatureLifecycleEffectSupport.swift",
                "Features/Home/HomeFeatureLoadFailureSupport.swift",
                "Features/Home/HomeFeatureState.swift",
                "Features/Home/HomeFeatureTaskDetailActionRouter.swift",
                "Features/Home/HomeFilterState.swift",
                "Features/Home/HomeFilterPresentation.swift",
                "Features/Home/HomeFilterSupport.swift",
                "Features/Home/HomeFeaturePostMutationRefresher.swift",
                "Features/Home/HomeFeaturePresentationRouter.swift",
                "Features/Home/HomeFeatureSelectionRouter.swift",
                "Features/Home/HomeFeatureTaskListModeRouter.swift",
                "Features/Home/IOSFirstTaskExperience.swift",
                "Features/Home/HomeReloadGuardSupport.swift",
                "Features/Home/HomeSelectionSupport.swift",
                "Features/Home/HomeCustomTaskSection.swift",
                "Features/Home/BacklogFeature.swift",
                "Features/Home/BacklogTaskListPresentation.swift",
                "Features/Home/TaskRankingFeature.swift",
                "Features/Home/TaskRankingPresentation.swift",
                "Features/Home/HomeTaskDeletionSupport.swift",
                "Features/Home/HomeTaskListDisplay.swift",
                "Features/Home/HomeTaskAdvancedQuery.swift",
                "Features/Home/HomeTaskListFiltering.swift",
                "Features/Home/HomeTaskListMetrics.swift",
                "Features/Home/HomeTaskListPredicate.swift",
                "Features/Home/HomeTaskListPresentation.swift",
                "Features/Home/HomeTaskListPresentation+iOS.swift",
                "Features/Home/HomeTaskListPresentation+Sidebar.swift",
                "Features/Home/HomeTaskListPresentation+SidebarGroups.swift",
                "Features/Home/HomeTaskListPresentationModels.swift",
                "Features/Home/HomeIOSPresentationSnapshot.swift",
                "Features/Home/HomeTaskListSectionBuilder.swift",
                "Features/Home/HomeTaskListSorter.swift",
                "Features/Home/HomeTaskListMode.swift",
                "Features/Home/HomeTaskRowVisibility.swift",
                "Features/Home/HomeTimelineRowVisibility.swift",
                "Features/Home/HomeRoutineDisplay.swift",
                "Features/Home/HomeRoutineDisplayQuerySupport.swift",
                "Features/Home/HomeRoutineDisplayCore.swift",
                "Features/Home/HomeRoutineDisplayFactory.swift",
                "Features/Home/HomeRoutineMetadataDisplay.swift",
                "Features/Home/HomeRoutineDisplayMetadataPresentation.swift",
                "Features/Home/HomeRoutineDisplayBadgePresentation.swift",
                "Features/Home/StatsChartPresentation.swift",
                "Features/Home/StatsActiveItemsBreakdown.swift",
                "Features/Home/StatsCreatedTasksPresentation.swift",
                "Features/Home/StatsDashboardOrderSupport.swift",
                "Features/Home/StatsFilterPresentation.swift",
                "Features/Home/StatsFilterSummarySupport.swift",
                "Features/Home/StatsFlagFilterSupport.swift",
                "Features/Home/StatsFeatureDerivedStateSupport.swift",
                "Features/Home/StatsSummaryItemPresentation.swift",
                "Features/Home/StatsSummaryTaskListPresentation.swift",
                "Features/Home/StatsTaskFilterResolver.swift",
                "Features/Home/StatsTaskTypeMatrixFilterSupport.swift",
                "Features/Home/HomeFeatureTaskLoadEffectFactory.swift",
                "Features/Home/HomeFeatureTaskLoadHandler.swift",
                "Features/Home/HomeFeatureTaskLoadQuery.swift",
                "Features/Home/HomeFeatureTemporaryViewStateSupport.swift",
                "Features/Home/HomeTaskLoadSupport.swift",
                "Features/Home/HomeTaskOrderingSupport.swift",
                "Features/Home/HomeTaskRowActionPresentation.swift",
                "Features/Home/HomeTaskSupport.swift",
                "Features/Home/HomeTagFilterMutationSupport.swift",
                "Features/Home/HomeTagFilterSupport.swift",
                "Features/Home/HomeFeatureTaskLifecycleCommandRouter.swift",
                "Features/Home/HomeTaskLifecycleCoordinator.swift",
                "Features/Home/HomeTaskLifecycleSupport.swift",
                "Features/Home/HomeTaskLifecycleExecutionSupport.swift",
                "Features/Settings/SettingsFeature.swift",
                "Features/Settings/SettingsFeatureState.swift",
                "Features/Settings/SettingsAutoAssumeDoneFlagRuleSupport.swift",
                "Features/Settings/SettingsAppearanceActionSupport.swift",
                "Features/Settings/SettingsAppearanceSupport.swift",
                "Features/Settings/SettingsAppIconActionSupport.swift",
                "Features/Settings/SettingsAppInteractionExecutionSupport.swift",
                "Features/Settings/SettingsCloudActionExecutionSupport.swift",
                "Features/Settings/SettingsCloudExecutionSupport.swift",
                "Features/Settings/SettingsCloudSupport.swift",
                "Features/Settings/SettingsCloudUsageEstimate.swift",
                "Features/Settings/SettingsCloudViewSupport.swift",
                "Features/Settings/SettingsDataQuerySupport.swift",
                "Features/Settings/SettingsDiagnosticsSupport.swift",
                "Features/Settings/SettingsExecutionSupport.swift",
                "Features/Settings/SettingsFeedbackSupport.swift",
                "Features/Settings/SettingsFastFilterActionSupport.swift",
                "Features/Settings/SettingsGitConnectionActionSupport.swift",
                "Features/Settings/SettingsGitLabSupport.swift",
                "Features/Settings/SettingsNotificationsExecutionSupport.swift",
                "Features/Settings/SettingsNotificationsSupport.swift",
                "Features/Settings/SettingsPlaceActionSupport.swift",
                "Features/Settings/SettingsPlaceSupport.swift",
                "Features/Settings/SettingsPlaceExecutionSupport.swift",
                "Features/Settings/SettingsPlacesViewSupport.swift",
                "Features/Settings/SettingsPlacePersistenceSupport.swift",
                "Features/Settings/SettingsRefreshActionExecutionSupport.swift",
                "Features/Settings/SettingsRefreshExecutionSupport.swift",
                "Features/Settings/SettingsRefreshSupport.swift",
                "Features/Settings/SettingsRoutineDataBackupCoding.swift",
                "Features/Settings/SettingsRoutineDataBackupFileNaming.swift",
                "Features/Settings/SettingsRoutineDataBackupMapping.swift",
                "Features/Settings/SettingsRoutineDataBackupModels.swift",
                "Features/Settings/SettingsRoutineDataBackupPackageBuilder.swift",
                "Features/Settings/SettingsRoutineDataBackupAudit.swift",
                "Features/Settings/SettingsRoutineDataBackupVerification.swift",
                "Features/Settings/SettingsRoutineDataImportEntityInserter.swift",
                "Features/Settings/SettingsRoutineDataImportStoreResetter.swift",
                "Features/Settings/SettingsRoutineDataPersistenceSupport.swift",
                "Features/Settings/SettingsRoutineDataRecoveryStore.swift",
                "Features/Settings/SettingsRoutineDataTransferActionExecutionSupport.swift",
                "Features/Settings/SettingsRoutineDataTransferExecutionSupport.swift",
                "Features/Settings/SettingsRoutineDataTransferSupport.swift",
                "Features/Settings/SettingsSectionViewSupport.swift",
                "Features/Settings/SettingsSectionStyleSupport.swift",
                "Features/Settings/SettingsTagManagerRefreshActionSupport.swift",
                "Features/Settings/SettingsTagMetadataActionSupport.swift",
                "Features/Settings/SettingsTagMutationActionSupport.swift",
                "Features/Settings/SettingsTagSupport.swift",
                "Features/Settings/SettingsTagExecutionSupport.swift",
                "Features/Settings/SettingsTagPersistenceSupport.swift",
                "Features/TaskDetail/RoutinePauseArchivePresentation.swift",
                "Features/TaskDetail/RoutineTaskRelationshipMutationSupport.swift",
                "Features/TaskDetail/TaskDetailBasicEditActionHandler.swift",
                "Features/TaskDetail/TaskDetailCompletionButtonTitlePresentation.swift",
                "Features/TaskDetail/TaskDetailCompletionLogActionHandler.swift",
                "Features/TaskDetail/TaskDetailDateMetadataPresentation.swift",
                "Features/TaskDetail/TaskDetailDialogLifecycleActionHandler.swift",
                "Features/TaskDetail/TaskDetailFetchDescriptors.swift",
                "Features/TaskDetail/TaskDetailEditContextActionHandler.swift",
                "Features/TaskDetail/TaskDetailEditDraftMutationHandler.swift",
                "Features/TaskDetail/TaskDetailEditSaveRequest.swift",
                "Features/TaskDetail/TaskDetailFeature+Action.swift",
                "Features/TaskDetail/TaskDetailFeature+ActionHandlers.swift",
                "Features/TaskDetail/TaskDetailFeature+ChecklistAndValueEffects.swift",
                "Features/TaskDetail/TaskDetailFeature+CompletionEffects.swift",
                "Features/TaskDetail/TaskDetailFeature+DetailContentEffects.swift",
                "Features/TaskDetail/TaskDetailFeature+EditEffects.swift",
                "Features/TaskDetail/TaskDetailFeature.swift",
                "Features/TaskDetail/TaskDetailFeature+State.swift",
                "Features/TaskDetail/TaskDetailFeature+Effects.swift",
                "Features/TaskDetail/TaskDetailFeature+FormSync.swift",
                "Features/TaskDetail/TaskDetailFeature+Helpers.swift",
                "Features/TaskDetail/TaskDetailFeature+LifecycleEffects.swift",
                "Features/TaskDetail/TaskDetailFeature+Presentation.swift",
                "Features/TaskDetail/TaskDetailFeature+StateDerivation.swift",
                "Features/TaskDetail/TaskDetailNotificationActionHandler.swift",
                "Features/TaskDetail/TaskDetailNotificationWarningPresentation.swift",
                "Features/TaskDetail/TaskDetailRecurrenceEditActionHandler.swift",
                "Features/TaskDetail/TaskDetailRoutineLifecycleActionHandler.swift",
                "Features/TaskDetail/TaskDetailStatusActionHandler.swift",
                "Features/TaskDetail/TaskDetailStepChecklistEditActionHandler.swift",
                "Features/TaskDetail/TaskDetailStatusMutationHandler.swift",
                "Features/TaskDetail/TaskDetailTagGoalRelationshipEditActionHandler.swift",
                "Persistence/PersistenceController.swift",
                "Persistence/RoutinaUndoSupport.swift",
                "Screens/TaskDetail/Graph/RelationshipGraphEdge.swift",
                "Screens/TaskDetail/Graph/TaskRelationshipGraphLayout.swift",
                "Screens/TaskDetail/TaskDetailAttachmentPresentation.swift",
                "Screens/TaskDetail/TaskDetailAttachmentActionRouter.swift",
                "Screens/TaskDetail/TaskDetailAttachmentTempFileSupport.swift",
                "Screens/TaskDetail/TaskDetailCalendarCardContent.swift",
                "Screens/TaskDetail/TaskDetailCalendarGridView.swift",
                "Screens/TaskDetail/TaskDetailCalendarGridSupport.swift",
                "Screens/TaskDetail/TaskDetailCalendarNavigation.swift",
                "Screens/TaskDetail/TaskDetailCalendarPresentation.swift",
                "Screens/TaskDetail/TaskDetailCalendarSectionView.swift",
                "Screens/TaskDetail/TaskDetailCalendarTodayButtonVisibility.swift",
                "Screens/TaskDetail/TaskDetailChecklistPresentation.swift",
                "Screens/TaskDetail/TaskDetailChecklistSectionView.swift",
                "Screens/TaskDetail/TaskDetailCommentsSectionView.swift",
                "Screens/TaskDetail/TaskDetailEditChangeSupport.swift",
                "Screens/TaskDetail/TaskDetailFocusSessionSectionView.swift",
                "Screens/TaskDetail/TaskDetailLogPresentation.swift",
                "Screens/TaskDetail/TaskDetailOverviewHeightsPreferenceKey.swift",
                "Screens/TaskDetail/TaskDetailValuePresentation.swift",
                "Screens/TaskDetail/TaskDetailRelationshipPresentation.swift",
                "Screens/TaskDetail/TaskDetailRelationshipsSectionView.swift",
                "Screens/TaskDetail/TaskDetailRoutineLogsSectionView.swift",
                "Screens/TaskDetail/TaskDetailSectionCardView.swift",
                "Screens/TaskDetail/TaskDetailSharedViewSupport.swift",
                "Screens/TaskDetail/TaskDetailDestinationSectionView.swift",
                "Screens/TaskDetail/TaskDetailPresentationRoutingSupport.swift",
                "Screens/TaskDetail/TaskDetailTimeEditingState.swift",
                "Screens/TaskDetail/TaskDetailMacTimeControlPresentation.swift",
                "Screens/TaskDetail/TaskDetailTimeSpentPresentation.swift",
                "Screens/Shared/AddRoutineTaskFormModelFactory.swift",
                "Screens/Shared/TaskDestinationFormEditor.swift",
                "Screens/Shared/TaskFormModel.swift",
                "Features/CalendarTaskImportFeature.swift",
                "Services/NotificationCoordinator.swift",
                "Services/BatteryRoutineService.swift",
                "Services/CalendarTaskImportService.swift",
                "Services/MicrosoftGraphCalendarService.swift",
                "Services/RoutinaQuickAddService.swift",
                "Services/DeviceActivityRecorder.swift",
                "Services/FocusShieldSupport.swift",
                "Services/FocusSessionSupport.swift",
                "Services/AwaySessionSupport.swift",
                "Services/SleepSessionSupport.swift",
                "Services/RoutinaCrashReporter.swift",
                "Services/RoutinaPerformanceProfiler.swift",
                "Services/RoutinaMacScrollInteractionGate.swift",
                "Services/PlaceCheckInSupport.swift",
                "Services/WidgetStatsService.swift",
                "Services/FocusTimerLiveActivityService.swift",
                "Services/FocusTimerWidgetService.swift",
                "Services/SprintBoardClient.swift",
                "Sync/CloudDataResetService.swift",
                "Sync/CloudSharingService.swift",
                "Sync/CloudKitDirectPullCanonicalIDResolver.swift",
                "Sync/CloudKitDirectPullDeletionHandler.swift",
                "Sync/CloudKitDirectPullEntityLookup.swift",
                "Sync/CloudKitDirectPullEntityPayloadAppliers.swift",
                "Sync/CloudKitDirectPullFetcher.swift",
                "Sync/CloudKitDirectPullMergeHousekeeping.swift",
                "Sync/CloudKitDirectPullMergeSupport.swift",
                "Sync/CloudKitDirectPullPayloadBatch.swift",
                "Sync/CloudKitDirectPullTaskPayloadApplier.swift",
                "Sync/CloudKitDirectPullRecordParser.swift",
                "Sync/CloudKitDirectPullService.swift",
                "Sync/CloudKitDirectPullSupport.swift",
                "Sync/CloudKitDirectPullTaskRecordParser.swift",
                "Sync/CloudKitDirectPullUpserter.swift",
                "Sync/CloudKitPushSubscriptionService.swift",
                "Sync/CloudSyncedSurfaceRefreshCoordinator.swift",
                "Sync/CloudKitSyncDiagnostics.swift",
                "Sync/CloudSyncClient.swift",
                "Sync/RoutineDuplicateIDCleanup.swift",
                "Views/HomeActiveFilterChipBar.swift",
                "Views/HomeAdvancedQueryBuilder.swift",
                "Views/HomeFilterControlModels.swift",
                "Views/HomeFilterChipButton.swift",
                "Views/HomeFilterFlowLayout.swift",
                "Views/HomeTaskRowColorMarkerShape.swift",
                "Views/HomeTodoStateFilterChips.swift",
                "Views/RoutinaLiquidGlass.swift",
                "Views/RoutinaDeepLinkShareViews.swift",
                "Screens/Home/HomeStatusAndEmptyViews.swift",
                "Views/AddRoutineAvailableTagSuggestionsView.swift",
                "Views/AddRoutineChecklistItemComposerView.swift",
                "Views/AddRoutineChecklistItemsView.swift",
                "Views/AddRoutineEditableStepsView.swift",
                "Views/AddRoutineImageAttachmentContent.swift",
                "Views/RecurrenceSelectionControls.swift",
                "Views/AddRoutineRepeatPatternSections.swift",
                "Views/AddRoutineSelectedTagsView.swift",
                "Views/AddRoutineStepComposerView.swift",
                "Views/AddRoutineTagComposerView.swift",
                "Views/QuickAddTaskSheet.swift",
                "Views/TaskImageView.swift",
                "Views/PlaceLocationPickerCameraConfiguration.swift",
                "Views/FocusSessionCard.swift",
                "Views/FocusSessionCardContent.swift",
                "Views/GoalsEditorForm.swift",
                "Views/ImportanceUrgencyMatrixPicker.swift",
                "Views/StatsDashboardComponents.swift",
                "Views/StatsDashboardPalette.swift",
                "Views/StatsDashboardReorderDropDelegate.swift",
                "Views/StatsDashboardScrollContainer.swift",
                "Views/StatsChartInsightBuilder.swift",
                "Views/StatsCompletionChartSection.swift",
                "Views/StatsCreatedTasksChartSection.swift",
                "Views/StatsEmotionTrendSection.swift",
                "Views/StatsEstimateActualChartSection.swift",
                "Views/StatsFocusChartSection.swift",
                "Views/StatsFocusAchievementsSection.swift",
                "Views/StatsFocusWorkChartSection.swift",
                "Views/StatsGoalProgressSection.swift",
                "Views/StatsHeroSectionView.swift",
                "Views/StatsTagUsageSection.swift",
                "Views/StatsSummaryGrid.swift",
                "Views/StatsSummaryCardItemBuilder.swift",
                "Views/TimelinePigmentControl.swift",
                "Views/UnassignedFocusSessionsCard.swift",
                "Views/SettingsQuickAddSyntaxViews.swift",
                "Views/SettingsTaskRowPreviewView.swift",
                "Views/AwayModeViews.swift",
                "Views/AwaySessionEditViews.swift",
                "Views/AwaySessionPresentationSupport.swift",
                "Views/AwaySessionStartComponents.swift",
                "Views/AwaySessionStartSheet.swift",
                "Views/SleepModeViews.swift",
                "Views/PlaceCheckInDockView.swift",
                "Views/PlaceCheckInMapSheet.swift",
                "Views/PlaceCheckInMapSheetContent.swift",
                "Views/PlaceCheckInMapSheetSupport.swift",
                "Views/EmotionLogContextLinkPicker.swift",
                "Views/EmotionLogQuickPresetButton.swift",
                "Views/EmotionLogViews.swift",
                "Views/RoutineNoteViews.swift",
                "Views/RoutineEventViews.swift",
                "Views/TaskRelationshipsEditor.swift",
                "Views/TaskVoiceNoteViews.swift",
                "Views/CalendarTaskSuggestionRowPresentation.swift",
                "Views/CalendarTaskImportSheet.swift",
                "Views/DayPlan/DayPlanPlannerPresentationModels.swift",
                "Views/DayPlan/DayPlanPlannerState.swift",
                "Views/DayPlan/DayPlanPlannerState+Undo.swift",
                "Views/DayPlan/DayPlanPlannerUndoModels.swift",
                "Views/DayPlan/DayPlanViewSupportTypes.swift",
                "Views/DayPlan/DayPlanCalendarListRowVisibility.swift",
                "Views/DayPlan/DayPlanDayTaskListCaches.swift",
                "Views/DayPlan/DayPlanDayTaskListModels.swift",
                "Views/DayPlan/DayPlanDayTaskListPresentation.swift",
                "Views/DayPlan/DayPlanSupport.swift",
                "Views/DayPlan/DayPlanBlockLayer.swift",
                "Views/DayPlan/DayPlanBlockCard.swift",
                "Views/DayPlan/DayPlanCurrentTimeIndicator.swift",
                "Views/DayPlan/DayPlanCurrentTimeScrollAnchor.swift",
                "Views/DayPlan/DayPlanDatePickerSidebar.swift",
                "Views/DayPlan/DayPlanDetailView.swift",
                "Views/DayPlan/DayPlanDropIndicator.swift",
                "Views/DayPlan/DayPlanFilterSidebars.swift",
                "Views/DayPlan/DayPlanHeaderUtilityControls.swift",
                "Views/DayPlan/DayPlanHeaderView.swift",
                "Views/DayPlan/DayPlanResizeHandle.swift",
                "Views/DayPlan/DayPlanRootViews.swift",
                "Views/DayPlan/DayPlanScrollTarget.swift",
                "Views/DayPlan/DayPlanSlotSelectionLayer.swift",
                "Views/DayPlan/DayPlanTaskAvatar.swift",
                "Views/DayPlan/DayPlanTaskDropSupport.swift",
                "Views/DayPlan/DayPlanAllDayBlocksCache.swift",
                "Views/DayPlan/DayPlanAllDaySupport.swift",
                "Views/DayPlan/DayPlanFocusSessionBlocks.swift",
                "Views/DayPlan/DayPlanFocusSessionPlannerAllocation.swift",
                "Views/DayPlan/DayPlanFocusSessionPlannerBlocks.swift",
                "Views/DayPlan/DayPlanFocusSessionPlannerCountUp.swift",
                "Views/DayPlan/DayPlanFocusSessionPlannerPersistence.swift",
                "Views/DayPlan/DayPlanFocusSessionPlannerSegments.swift",
                "Views/DayPlan/DayPlanFocusSessionPlannerSync.swift",
                "Views/DayPlan/DayPlanSprintFocusBlocks.swift",
                "Views/DayPlan/DayPlanSessionSupport.swift",
                "Views/DayPlan/DayPlanSlotActionComponents.swift",
                "Views/DayPlan/DayPlanSlotActionSidebar.swift",
                "Views/DayPlan/DayPlanTagFocusSidebar.swift",
                "Views/DayPlan/DayPlanTimelineDataSnapshot.swift",
                "Views/DayPlan/DayPlanTimelinePanelView.swift",
                "Views/DayPlan/DayPlanTimelinePlacementCache.swift",
                "Views/DayPlan/DayPlanTimelinePlacementCacheKey.swift",
                "Views/DayPlan/DayPlanTimelineRenderSnapshot.swift",
                "Views/DayPlan/DayPlanTimelineRenderSnapshotCache.swift",
                "Views/DayPlan/DayPlanWeekDayHeader.swift",
                "Views/DayPlan/DayPlanWeekHeaderRow.swift",
                "Views/DayPlan/DayPlanWeekGridView.swift",
                "Views/DayPlan/DayPlanDayTaskColumnsView.swift",
                "Views/DayPlan/DayPlanDayTaskListContentView.swift",
                "Views/DayPlan/DayPlanSlotDraftViews.swift",
                "Views/DayPlan/DayPlanWeekCalendarView.swift",
                "Views/DayPlan/DayPlanWeekCalendarLanes.swift",
                "Views/DayPlan/DayPlanWeekCalendarScrollSupport.swift",
                "Views/DayPlan/DayPlanWeekCalendarSizing.swift",
                "Views/DayPlan/DayPlanPresentationSheets.swift",
                "Views/DayPlan/DayPlanProtectedSessionBlocksCache.swift",
                "Views/DayPlan/DayPlanTimelineSupport.swift",
                "Views/DayPlan/DayPlanVisibleBlockContextCache.swift",
                "Views/DayPlanView.swift",
                "Views/RoutinaPerformanceProfilingLifecycleView.swift",
                "Views/RoutineTagColor.swift",
                "Views/TodoStateTimingSectionView.swift",
                "Services/GitStatsCredentialStore.swift",
                "Services/GitStatsFileStore.swift",
                "Services/GitHubProfileStatsSupport.swift",
                "Services/GitHubRepositoryStatsSupport.swift",
                "Services/GitHubStatsConnectionStore.swift",
                "Services/GitHubStatsClient.swift",
                "Services/GitHubStatsGraphQLSupport.swift",
                "Services/GitHubStatsPayloads.swift",
                "Services/GitHubStatsRESTSupport.swift",
                "Services/GitHubWidgetService.swift",
                "Services/GitLabStatsClient.swift",
                "Services/GitLabStatsSupport.swift",
                "Services/GitLabWidgetService.swift",
                "Services/MacAppWidgetAvailability.swift",
                "Views/AppLockGate.swift",
            ]
        ),
        .target(
            name: "RoutinaMacSupport",
            path: "RoutinaMacApp",
            exclude: [
                "AddEditFormCoordinator.swift",
                "Features",
                "FormSection.swift",
                "RoutinaMacApp.swift",
                "Screens",
                "Utilities/MacBatteryRoutineMonitor.swift",
                "Utilities/LocationProvider.swift",
                "Utilities/MacQuickAddShortcut.swift",
                "Utilities/PlatformClients.swift",
                "Utilities/PlatformSupport+AppKit.swift",
                "Utilities/RemoteNotificationMacDelegate.swift",
                "Utilities/RoutinaMacAIReadOnlySnapshotScheduler.swift",
                "Utilities/RoutinaMacGlobalHotKey.swift",
                "Utilities/RoutinaMacUndoBridge.swift",
            ],
            sources: [
                "Commands",
                "Utilities/MacMenuCleanup.swift",
            ]
        ),
        .executableTarget(
            name: "RoutinaAIMVPCLI",
            dependencies: ["RoutinaAppSupport"],
            path: "Tools/RoutinaAIMVPCLI"
        ),
        .target(
            name: "RoutinaHelpSupport",
            path: "SharedCore/Help"
        ),
        .executableTarget(
            name: "RoutinaAIMCPServer",
            dependencies: ["RoutinaHelpSupport"],
            path: "Tools/RoutinaAIMCPServer",
            exclude: ["smoke-test.jsonl"]
        ),
        .executableTarget(
            name: "RoutinaBackupAudit",
            dependencies: ["RoutinaAppSupport"],
            path: "Tools/RoutinaBackupAudit"
        ),
        .testTarget(
            name: "RoutinaAppSupportTests",
            dependencies: [
                "RoutinaAppSupport",
                "RoutinaHelpSupport",
                .product(name: "ComposableArchitecture", package: "swift-composable-architecture"),
                .product(name: "Dependencies", package: "swift-dependencies"),
            ],
            path: "Tests/Shared"
        ),
    ]
)
