// swift-tools-version: 6.0

import PackageDescription

let package = Package(
    name: "RoutinaModules",
    platforms: [
        .iOS("18.0"),
        .macOS("15.0"),
    ],
    products: [
        .library(
            name: "RoutinaAppSupport",
            targets: ["RoutinaAppSupport"]
        ),
        .library(
            name: "RoutinaMacSupport",
            targets: ["RoutinaMacSupport"]
        ),
        .executable(
            name: "RoutinaAIMVPCLI",
            targets: ["RoutinaAIMVPCLI"]
        ),
        .executable(
            name: "RoutinaAIMCPServer",
            targets: ["RoutinaAIMCPServer"]
        ),
    ],
    dependencies: [
        .package(
            url: "https://github.com/pointfreeco/swift-composable-architecture",
            from: "1.24.1"
        ),
        .package(
            url: "https://github.com/pointfreeco/swift-dependencies",
            from: "1.4.0"
        ),
        .package(
            url: "https://github.com/pointfreeco/swift-case-paths",
            from: "1.5.4"
        ),
        .package(
            url: "https://github.com/pointfreeco/swift-perception",
            from: "1.3.4"
        ),
        .package(
            url: "https://github.com/pointfreeco/swift-concurrency-extras",
            from: "1.2.0"
        ),
    ],
    targets: [
        .target(
            name: "RoutinaAppSupport",
            dependencies: [
                .product(name: "ComposableArchitecture", package: "swift-composable-architecture"),
                .product(name: "Dependencies", package: "swift-dependencies"),
                .product(name: "CasePaths", package: "swift-case-paths"),
                .product(name: "Perception", package: "swift-perception"),
                .product(name: "PerceptionCore", package: "swift-perception"),
                .product(name: "ConcurrencyExtras", package: "swift-concurrency-extras"),
            ],
            path: ".",
            exclude: [
                ".build",
                ".claude",
                ".git",
                ".gitignore",
                ".swiftpm",
                ".xcresulttmp",
                ".DS_Store",
                "Package.resolved",
                "Package.swift",
                "Routina.xcworkspace",
                "RoutinaiOS.xcodeproj",
                "RoutinaMacOS.xcodeproj",
                "RoutinaWidget",
                "RoutinaWidgetExtension.entitlements",
                "Tools",
                "build",
                "Config",
                "AppResources",
                "docs",
                "iOS",
                "RoutinaMacApp",
                "RoutinaWatchApp",
                "RoutinaWatchExtension",
                "Tests",
                "mac+watch+ios",
                // Files that live in SharedCore but cannot yet be compiled as
                // part of the RoutinaAppSupport package target. Each needs a
                // dedicated migration step before it can move in.
                //
                // Blocked on AppFeature (top-level TCA reducer still lives in
                // the per-app Xcode targets):
                "SharedCore/App/RoutinaAppBootstrap.swift",
                "SharedCore/App/RoutinaAppSceneBootstrap.swift",
                // TODO(styling-injection): These reference TaskDetailPlatformStyle,
                // a per-app enum of UI constants (fonts/colors/padding). The two
                // per-app copies share an API but no implementation, so a naive
                // `#if canImport(UIKit/AppKit)` merge is copy-paste dressed up as
                // sharing and inverts layering (SharedCore picking platform UI
                // tokens). Design a proper injection path — e.g. a
                // `TaskDetailStyling` protocol with per-app conforming values
                // injected via TCA dependency or SwiftUI environment — then move
                // these files in and drop the per-app TaskDetailPlatformStyle.swift
                // copies under iOS/ and RoutinaMacApp/.
                "SharedCore/Screens/TaskDetail/TaskDetailPresentation.swift",
                "SharedCore/Screens/TaskDetail/Graph/RelationshipGraphNodeCard.swift",
                // Blocked on per-app view modifiers (routinaInlineTitleDisplayMode,
                // routinaGraphSheetFrame) plus TaskDetailPlatformStyle above:
                "SharedCore/Screens/TaskDetail/Graph/TaskRelationshipGraphSheet.swift",
                // Not yet audited:
                "SharedCore/Screens/TaskDetail/TaskDetailHeaderViews.swift",
                // Extends the per-app HomeTCAView type and is compiled by both
                // Xcode app targets through the shared source folder.
                "SharedCore/Screens/Home/HomeTCAView+ViewState.swift",
                "SharedCore/Screens/Home/HomeTCAView+Refresh.swift",
            ],
            sources: [
                "SharedCore/App/AppEnvironment.swift",
                "SharedCore/App/RoutinaAppIntents.swift",
                "SharedCore/App/RoutinaUITestSeeder.swift",
                "SharedCore/AI",
                "SharedCore/Models",
                "SharedCore/Dependencies/AppIconClient.swift",
                "SharedCore/Dependencies/DeviceAuthenticationClient.swift",
                "SharedCore/Dependencies/DependencyValues+.swift",
                "SharedCore/Dependencies/LocationClient.swift",
                "SharedCore/Dependencies/NotificationClient.swift",
                "SharedCore/Dependencies/PlatformSupport.swift",
                "SharedCore/Dependencies/UserDefaultsProtocol.swift",
                "SharedCore/Domain/EmojiCatalog.swift",
                "SharedCore/Domain/NotificationPreferences.swift",
                "SharedCore/Domain/RoutineCompletionStats.swift",
                "SharedCore/Domain/WidgetStats.swift",
                "SharedCore/Domain/RoutineAssumedCompletion.swift",
                "SharedCore/Domain/RoutineDateMath.swift",
                "SharedCore/Domain/RoutineListFilter.swift",
                "SharedCore/Domain/RoutineListSectioningMode.swift",
                "SharedCore/Domain/RoutineLogHistory.swift",
                "SharedCore/Domain/RoutinaQuickAddParser.swift",
                "SharedCore/Domain/RoutineTag.swift",
                "SharedCore/Domain/FastFilterTags.swift",
                "SharedCore/Domain/GitHubStatsModels.swift",
                "SharedCore/Domain/GitHubWidgetData.swift",
                "SharedCore/Domain/GitLabWidgetData.swift",
                "SharedCore/Domain/SprintBoardModels.swift",
                "SharedCore/Domain/TagCounterDisplayMode.swift",
                "SharedCore/Domain/TagCounterFormatting.swift",
                "SharedCore/Domain/Tab.swift",
                "SharedCore/Domain/TabFilterStateManager.swift",
                "SharedCore/Domain/TaskImageProcessor.swift",
                "SharedCore/Domain/TimelineLogic.swift",
                "SharedCore/Domain/TodoStateTiming.swift",
                "SharedCore/Dependencies/RoutineDataTransferClient.swift",
                "SharedCore/Features/Timeline/TimelineFeature.swift",
                "SharedCore/Features/AddRoutine/AddRoutineFeature.swift",
                "SharedCore/Features/AddRoutine/AddRoutineBasicsSupport.swift",
                "SharedCore/Features/AddRoutine/AddRoutineChecklistSupport.swift",
                "SharedCore/Features/AddRoutine/AddRoutineFormSupport.swift",
                "SharedCore/Features/AddRoutine/AddRoutineOrganizationSupport.swift",
                "SharedCore/Features/AddRoutine/AddRoutineScheduleSupport.swift",
                "SharedCore/Features/AddRoutine/AddRoutineSaveSupport.swift",
                "SharedCore/Features/AddRoutine/AddRoutineFeatureState.swift",
                "SharedCore/Features/AddRoutine/AddRoutineValidationSupport.swift",
                "SharedCore/Features/AddRoutine/TaskFormPresentation.swift",
                "SharedCore/Features/Goals/GoalsFeature.swift",
                "SharedCore/Features/Home/AppFeatureTemporaryViewStateSupport.swift",
                "SharedCore/Features/Home/HomeBoardMutationSupport.swift",
                "SharedCore/Features/Home/HomeAddRoutineSupport.swift",
                "SharedCore/Features/Home/HomeAdvancedQueryInputSupport.swift",
                "SharedCore/Features/Home/HomeFeatureAddRoutinePresentationRouter.swift",
                "SharedCore/Features/Home/HomeDeduplicationSupport.swift",
                "SharedCore/Features/Home/HomeDetailSelectionSupport.swift",
                "SharedCore/Features/Home/HomeDisplayFilterSupport.swift",
                "SharedCore/Features/Home/HomeFeatureFilterMutationHandler.swift",
                "SharedCore/Features/Home/HomeFeatureState.swift",
                "SharedCore/Features/Home/HomeFilterState.swift",
                "SharedCore/Features/Home/HomeFilterPresentation.swift",
                "SharedCore/Features/Home/HomeFilterSupport.swift",
                "SharedCore/Features/Home/HomeFeaturePostMutationRefresher.swift",
                "SharedCore/Features/Home/HomeFeaturePresentationRouter.swift",
                "SharedCore/Features/Home/HomeFeatureSelectionRouter.swift",
                "SharedCore/Features/Home/HomeFeatureTaskListModeRouter.swift",
                "SharedCore/Features/Home/HomeReloadGuardSupport.swift",
                "SharedCore/Features/Home/HomeSelectionSupport.swift",
                "SharedCore/Features/Home/HomeTaskDeletionSupport.swift",
                "SharedCore/Features/Home/HomeTaskListDisplay.swift",
                "SharedCore/Features/Home/HomeTaskAdvancedQuery.swift",
                "SharedCore/Features/Home/HomeTaskListFiltering.swift",
                "SharedCore/Features/Home/HomeTaskListMetrics.swift",
                "SharedCore/Features/Home/HomeTaskListPredicate.swift",
                "SharedCore/Features/Home/HomeTaskListPresentation.swift",
                "SharedCore/Features/Home/HomeTaskListSectionBuilder.swift",
                "SharedCore/Features/Home/HomeTaskListSorter.swift",
                "SharedCore/Features/Home/HomeRoutineMetadataDisplay.swift",
                "SharedCore/Features/Home/HomeRoutineDisplayMetadataPresentation.swift",
                "SharedCore/Features/Home/HomeRoutineDisplayBadgePresentation.swift",
                "SharedCore/Features/Home/StatsChartPresentation.swift",
                "SharedCore/Features/Home/StatsActiveItemsBreakdown.swift",
                "SharedCore/Features/Home/StatsCreatedTasksPresentation.swift",
                "SharedCore/Features/Home/StatsFilterPresentation.swift",
                "SharedCore/Features/Home/StatsFeatureDerivedStateSupport.swift",
                "SharedCore/Features/Home/StatsSummaryItemPresentation.swift",
                "SharedCore/Features/Home/StatsTaskFilterResolver.swift",
                "SharedCore/Features/Home/HomeFeatureTaskLoadEffectFactory.swift",
                "SharedCore/Features/Home/HomeFeatureTaskLoadHandler.swift",
                "SharedCore/Features/Home/HomeFeatureTemporaryViewStateSupport.swift",
                "SharedCore/Features/Home/HomeTaskLoadSupport.swift",
                "SharedCore/Features/Home/HomeTaskOrderingSupport.swift",
                "SharedCore/Features/Home/HomeTaskRowActionPresentation.swift",
                "SharedCore/Features/Home/HomeTaskSupport.swift",
                "SharedCore/Features/Home/HomeTagFilterSupport.swift",
                "SharedCore/Features/Home/HomeTaskLifecycleCoordinator.swift",
                "SharedCore/Features/Home/HomeTaskLifecycleSupport.swift",
                "SharedCore/Features/Home/HomeTaskLifecycleExecutionSupport.swift",
                "SharedCore/Features/Settings/SettingsFeature.swift",
                "SharedCore/Features/Settings/SettingsFeatureState.swift",
                "SharedCore/Features/Settings/SettingsAppearanceSupport.swift",
                "SharedCore/Features/Settings/SettingsAppInteractionExecutionSupport.swift",
                "SharedCore/Features/Settings/SettingsCloudActionExecutionSupport.swift",
                "SharedCore/Features/Settings/SettingsCloudExecutionSupport.swift",
                "SharedCore/Features/Settings/SettingsCloudSupport.swift",
                "SharedCore/Features/Settings/SettingsCloudUsageEstimate.swift",
                "SharedCore/Features/Settings/SettingsCloudViewSupport.swift",
                "SharedCore/Features/Settings/SettingsDataQuerySupport.swift",
                "SharedCore/Features/Settings/SettingsDiagnosticsSupport.swift",
                "SharedCore/Features/Settings/SettingsExecutionSupport.swift",
                "SharedCore/Features/Settings/SettingsFeedbackSupport.swift",
                "SharedCore/Features/Settings/SettingsGitLabSupport.swift",
                "SharedCore/Features/Settings/SettingsNotificationsExecutionSupport.swift",
                "SharedCore/Features/Settings/SettingsNotificationsSupport.swift",
                "SharedCore/Features/Settings/SettingsPlaceSupport.swift",
                "SharedCore/Features/Settings/SettingsPlaceExecutionSupport.swift",
                "SharedCore/Features/Settings/SettingsPlacesViewSupport.swift",
                "SharedCore/Features/Settings/SettingsPlacePersistenceSupport.swift",
                "SharedCore/Features/Settings/SettingsRefreshExecutionSupport.swift",
                "SharedCore/Features/Settings/SettingsRefreshSupport.swift",
                "SharedCore/Features/Settings/SettingsRoutineDataPersistenceSupport.swift",
                "SharedCore/Features/Settings/SettingsRoutineDataTransferActionExecutionSupport.swift",
                "SharedCore/Features/Settings/SettingsRoutineDataTransferExecutionSupport.swift",
                "SharedCore/Features/Settings/SettingsRoutineDataTransferSupport.swift",
                "SharedCore/Features/Settings/SettingsSectionViewSupport.swift",
                "SharedCore/Features/Settings/SettingsTagSupport.swift",
                "SharedCore/Features/Settings/SettingsTagExecutionSupport.swift",
                "SharedCore/Features/Settings/SettingsTagPersistenceSupport.swift",
                "SharedCore/Features/TaskDetail/RoutinePauseArchivePresentation.swift",
                "SharedCore/Features/TaskDetail/TaskDetailFeature.swift",
                "SharedCore/Features/TaskDetail/TaskDetailFeature+Effects.swift",
                "SharedCore/Features/TaskDetail/TaskDetailFeature+FormSync.swift",
                "SharedCore/Features/TaskDetail/TaskDetailFeature+Helpers.swift",
                "SharedCore/Features/TaskDetail/TaskDetailFeature+Presentation.swift",
                "SharedCore/Features/TaskDetail/TaskDetailFeature+StateDerivation.swift",
                "SharedCore/Persistence/PersistenceController.swift",
                "SharedCore/Screens/TaskDetail/Graph/RelationshipGraphEdge.swift",
                "SharedCore/Screens/TaskDetail/Graph/TaskRelationshipGraphLayout.swift",
                "SharedCore/Screens/TaskDetail/TaskDetailAttachmentPresentation.swift",
                "SharedCore/Screens/TaskDetail/TaskDetailCalendarGridView.swift",
                "SharedCore/Screens/TaskDetail/TaskDetailCalendarPresentation.swift",
                "SharedCore/Screens/TaskDetail/TaskDetailCalendarSectionView.swift",
                "SharedCore/Screens/TaskDetail/TaskDetailChecklistPresentation.swift",
                "SharedCore/Screens/TaskDetail/TaskDetailChecklistSectionView.swift",
                "SharedCore/Screens/TaskDetail/TaskDetailEditChangeSupport.swift",
                "SharedCore/Screens/TaskDetail/TaskDetailLogPresentation.swift",
                "SharedCore/Screens/TaskDetail/TaskDetailPriorityPresentation.swift",
                "SharedCore/Screens/TaskDetail/TaskDetailRelationshipPresentation.swift",
                "SharedCore/Screens/TaskDetail/TaskDetailRelationshipsSectionView.swift",
                "SharedCore/Screens/TaskDetail/TaskDetailRoutineLogsSectionView.swift",
                "SharedCore/Screens/TaskDetail/TaskDetailSectionCardView.swift",
                "SharedCore/Screens/TaskDetail/TaskDetailSharedViewSupport.swift",
                "SharedCore/Screens/TaskDetail/TaskDetailTaskChangesSectionView.swift",
                "SharedCore/Screens/TaskDetail/TaskDetailTimeSpentPresentation.swift",
                "SharedCore/Services/NotificationCoordinator.swift",
                "SharedCore/Services/CalendarTaskImportService.swift",
                "SharedCore/Services/MicrosoftGraphCalendarService.swift",
                "SharedCore/Services/RoutinaQuickAddService.swift",
                "SharedCore/Services/WidgetStatsService.swift",
                "SharedCore/Services/SprintBoardClient.swift",
                "SharedCore/Sync/CloudDataResetService.swift",
                "SharedCore/Sync/CloudSharingService.swift",
                "SharedCore/Sync/CloudKitDirectPullService.swift",
                "SharedCore/Sync/CloudKitDirectPullSupport.swift",
                "SharedCore/Sync/CloudKitPushSubscriptionService.swift",
                "SharedCore/Sync/CloudKitSyncDiagnostics.swift",
                "SharedCore/Sync/CloudSyncClient.swift",
                "SharedCore/Sync/RoutineDuplicateIDCleanup.swift",
                "SharedCore/Views/HomeActiveFilterChipBar.swift",
                "SharedCore/Views/HomeAdvancedQueryBuilder.swift",
                "SharedCore/Views/HomeFilterControlModels.swift",
                "SharedCore/Views/HomeFilterChipButton.swift",
                "SharedCore/Views/HomeFilterFlowLayout.swift",
                "SharedCore/Views/HomeTodoStateFilterChips.swift",
                "SharedCore/Screens/Home/HomeStatusAndEmptyViews.swift",
                "SharedCore/Views/AddRoutineAvailableTagSuggestionsView.swift",
                "SharedCore/Views/AddRoutineChecklistItemComposerView.swift",
                "SharedCore/Views/AddRoutineChecklistItemsView.swift",
                "SharedCore/Views/AddRoutineEditableStepsView.swift",
                "SharedCore/Views/AddRoutineSelectedTagsView.swift",
                "SharedCore/Views/AddRoutineStepComposerView.swift",
                "SharedCore/Views/AddRoutineTagComposerView.swift",
                "SharedCore/Views/QuickAddTaskSheet.swift",
                "SharedCore/Views/FocusSessionCard.swift",
                "SharedCore/Views/GoalsEditorSheet.swift",
                "SharedCore/Views/ImportanceUrgencyMatrixPicker.swift",
                "SharedCore/Views/StatsDashboardComponents.swift",
                "SharedCore/Views/StatsDashboardPalette.swift",
                "SharedCore/Views/StatsDashboardScrollContainer.swift",
                "SharedCore/Views/StatsDataRefreshModifier.swift",
                "SharedCore/Views/StatsCompletionChartSection.swift",
                "SharedCore/Views/StatsFocusChartSection.swift",
                "SharedCore/Views/StatsHeroSectionView.swift",
                "SharedCore/Views/StatsTagUsageSection.swift",
                "SharedCore/Views/StatsSummaryGrid.swift",
                "SharedCore/Views/TaskRelationshipsEditor.swift",
                "SharedCore/Views/CalendarTaskImportSheet.swift",
                "SharedCore/Views/DayPlan/DayPlanPlannerState.swift",
                "SharedCore/Views/DayPlan/DayPlanSupport.swift",
                "SharedCore/Views/DayPlan/DayPlanBlockLayer.swift",
                "SharedCore/Views/DayPlan/DayPlanBlockCard.swift",
                "SharedCore/Views/DayPlan/DayPlanCurrentTimeIndicator.swift",
                "SharedCore/Views/DayPlan/DayPlanCurrentTimeScrollAnchor.swift",
                "SharedCore/Views/DayPlan/DayPlanDropIndicator.swift",
                "SharedCore/Views/DayPlan/DayPlanResizeHandle.swift",
                "SharedCore/Views/DayPlan/DayPlanScrollTarget.swift",
                "SharedCore/Views/DayPlan/DayPlanSlotSelectionLayer.swift",
                "SharedCore/Views/DayPlan/DayPlanTaskAvatar.swift",
                "SharedCore/Views/DayPlan/DayPlanTaskDropSupport.swift",
                "SharedCore/Views/DayPlan/DayPlanWeekDayHeader.swift",
                "SharedCore/Views/DayPlan/DayPlanWeekHeaderRow.swift",
                "SharedCore/Views/DayPlan/DayPlanWeekGridView.swift",
                "SharedCore/Views/DayPlan/DayPlanWeekCalendarView.swift",
                "SharedCore/Views/DayPlanView.swift",
                "SharedCore/Views/RoutineTagColor.swift",
                "SharedCore/Views/TodoStateTimingSectionView.swift",
                "SharedCore/Services/GitHubStatsClient.swift",
                "SharedCore/Services/GitHubWidgetService.swift",
                "SharedCore/Services/GitLabStatsClient.swift",
                "SharedCore/Services/GitLabWidgetService.swift",
                "SharedCore/Views/AppLockGate.swift",
            ]
        ),
        .target(
            name: "RoutinaMacSupport",
            path: "RoutinaMacApp",
            exclude: [
                "AddEditFormCoordinator.swift",
                "Features",
                "RoutinaMacApp.swift",
                "Screens",
                "Utilities/LocationProvider.swift",
                "Utilities/PlatformClients.swift",
                "Utilities/PlatformSupport+AppKit.swift",
                "Utilities/PlatformSupportBase.swift",
                "Utilities/RemoteNotificationMacDelegate.swift",
                "Utilities/RoutinaMacGlobalHotKey.swift",
            ],
            sources: [
                "Commands",
                "Utilities/MacMenuCleanup.swift",
            ]
        ),
        .executableTarget(
            name: "RoutinaAIMVPCLI",
            dependencies: ["RoutinaAppSupport"],
            path: "Tools/RoutinaAIMVPCLI"
        ),
        .executableTarget(
            name: "RoutinaAIMCPServer",
            dependencies: ["RoutinaAppSupport"],
            path: "Tools/RoutinaAIMCPServer",
            exclude: ["smoke-test.jsonl"]
        ),
        .testTarget(
            name: "RoutinaAppSupportTests",
            dependencies: [
                "RoutinaAppSupport",
                .product(name: "ComposableArchitecture", package: "swift-composable-architecture"),
                .product(name: "Dependencies", package: "swift-dependencies"),
            ],
            path: "Tests/Shared"
        ),
    ]
)
