import Foundation

extension TaskDetailFeature {
    typealias EditFrequency = TaskFormFrequencyUnit

    enum Action: Equatable {
        case markAsDone
        case cancelTodo
        case toggleChecklistRunoutItemDone(UUID)
        case extendChecklistItemRunout(UUID)
        case toggleChecklistItemCompletion(UUID)
        case markChecklistItemCompleted(UUID)
        case detailAddChecklistItemTapped
        case detailUpdateChecklistItem(UUID, title: String, intervalDays: Int)
        case requestUndoSelectedDateCompletion
        case undoSelectedDateCompletion
        case requestRemoveLogEntry(Date)
        case removeLogEntry(Date)
        case setManualCompletionConfirmation(Bool)
        case confirmManualCompletion([UUID])
        case updateTaskDuration(Int?)
        case updateLogDuration(UUID, Int?)
        case revealTodoStateInTaskDetail
        case revealImportanceInTaskDetail
        case revealUrgencyInTaskDetail
        case revealHeatmapInTaskDetail
        case revealHistoryInTaskDetail
        case taskDetailCalendarExpansionChanged(Bool)
        case pauseTapped
        case pauseUntilTapped(Date)
        case notTodayTapped
        case resumeTapped
        case startOngoingTapped
        case finishOngoingTapped
        case selectedDateChanged(Date)
        case selectOccurrence(Date)
        case markOccurrenceDone(Date)
        case markOccurrenceMissed(Date)
        case markOccurrenceCanceled(Date)
        case setEditSheet(Bool)
        case setAddDetailChooserPresented(Bool)
        case prepareInlineEdit
        case editRoutineNameChanged(String)
        case editCustomTaskSectionChanged(UUID?)
        case editRoutineEmojiChanged(String)
        case editTaskDescriptionChanged(String)
        case editRoutineNotesChanged(String)
        case detailCommentDraftChanged(String)
        case detailCommentAddTapped
        case detailCommentEditTapped(UUID)
        case detailCommentEditDraftChanged(String)
        case detailCommentEditCancelTapped
        case detailCommentEditSaveTapped(UUID)
        case detailCommentDeleteTapped(UUID)
        case detailLinkExistingTask(UUID, RoutineTaskRelationshipKind)
        case editRoutineLinkChanged(String)
        case editDeadlineEnabledChanged(Bool)
        case editDeadlineDateChanged(Date)
        case editAllDayChanged(Bool)
        case editRoutineDurationModeChanged(RoutineDurationMode)
        case editAvailabilityStartDateChanged(Date?)
        case editAvailabilityEndDateChanged(Date?)
        case editPlannedDateChanged(Date?)
        case editReminderEnabledChanged(Bool)
        case editReminderDateChanged(Date)
        case editReminderLeadMinutesChanged(Int?)
        case editPriorityChanged(RoutineTaskPriority)
        case editImportanceChanged(RoutineTaskImportance)
        case editUrgencyChanged(RoutineTaskUrgency)
        case editPressureChanged(RoutineTaskPressure)
        case editTemporalWeightRuleChanged(RoutineTaskTemporalWeightRule?)
        case editTaskLadderEntryWindowChanged(RoutineTaskLadderEntryWindow)
        case editThinkingNeededChanged(RoutineTaskThinkingNeeded)
        case editImagePicked(Data?)
        case editRemoveImageTapped
        case editVoiceNoteChanged(RoutineVoiceNote?)
        case editAttachmentPicked(Data, String)
        case editRemoveAttachment(UUID)
        case attachmentsLoaded([AttachmentItem])
        case editTagDraftChanged(String)
        case editFlagDraftChanged(String)
        case editGoalDraftChanged(String)
        case editAddTagTapped
        case editAddFlagTapped
        case editAddGoalTapped
        case editRemoveTag(String)
        case editRemoveFlag(String)
        case editRemoveGoal(UUID)
        case editAddRelationship(UUID, RoutineTaskRelationshipKind)
        case editRemoveRelationship(UUID)
        case editTagRenamed(oldName: String, newName: String)
        case editTagDeleted(String)
        case editScheduleModeChanged(RoutineScheduleMode)
        case editStepDraftChanged(String)
        case editAddStepTapped
        case editRemoveStep(UUID)
        case editMoveStepUp(UUID)
        case editMoveStepDown(UUID)
        case editChecklistItemDraftTitleChanged(String)
        case editChecklistItemDraftIntervalChanged(Int)
        case editAddChecklistItemTapped
        case editRemoveChecklistItem(UUID)
        case availablePlacesLoaded([RoutinePlaceSummary])
        case availableTagsLoaded([String])
        case availableFlagsLoaded([String])
        case flagRulesLoaded([RoutineFlagRule])
        case availableTagSummariesLoaded([RoutineTagSummary])
        case availableGoalsLoaded([RoutineGoalSummary])
        case availableEventsLoaded([RoutineEventLinkCandidate])
        case relatedTagRulesLoaded([RoutineRelatedTagRule])
        case availableRelationshipTasksLoaded([RoutineTaskRelationshipCandidate])
        case editSelectedPlaceChanged(UUID?)
        case editSelectedPlaceIDsChanged([UUID])
        case editDestinationAddressChanged(String)
        case editDestinationCoordinateChanged(LocationCoordinate?)
        case editToggleTagSelection(String)
        case editToggleFlagSelection(String)
        case editToggleGoalSelection(RoutineGoalSummary)
        case editToggleEventSelection(UUID)
        case editEstimatedDurationChanged(Int?)
        case editActualDurationChanged(Int?)
        case editStoryPointsChanged(Int?)
        case editFocusModeEnabledChanged(Bool)
        case editCadenceEnabledChanged(Bool)
        case editNudgesEnabledChanged(Bool)
        case editTaskLadderGroupEnabledChanged(Bool)
        case editFrequencyChanged(EditFrequency)
        case editFrequencyValueChanged(Int)
        case editRecurrenceEditorModeChanged(RoutineRecurrenceEditorMode)
        case editAdvancedRecurrenceRuleChanged(RoutineAdvancedRecurrenceRule)
        case editRecurrenceDraftChanged(RoutineRecurrenceDraft)
        case editRecurrenceKindChanged(RoutineRecurrenceRule.Kind)
        case editRecurrenceHasExplicitTimeChanged(Bool)
        case editRecurrenceHasTimeRangeChanged(Bool)
        case editRecurrenceTimeRangeRoleChanged(RoutineTimeRangeRole)
        case editRecurrenceTimeOfDayChanged(RoutineTimeOfDay)
        case editRecurrenceTimeRangeStartChanged(RoutineTimeOfDay)
        case editRecurrenceTimeRangeEndChanged(RoutineTimeOfDay)
        case editRecurrenceWeekdayChanged(Int)
        case editRecurrenceWeekdaysChanged([Int])
        case editRecurrenceDayOfMonthChanged(Int)
        case editRecurrenceDaysOfMonthChanged([Int])
        case editAutoAssumeDailyDoneChanged(Bool)
        case editHidesAssumedDoneCalendarBlockChanged(Bool)
        case editAutoAssumeDoneTimeOfDayChanged(RoutineTimeOfDay)
        case editSaveTapped
        case editSaveRejected(RoutineTask)
        case confirmAssumedPastDays
        case setDeleteConfirmation(Bool)
        case setUndoCompletionConfirmation(Bool)
        case confirmUndoCompletion
        case deleteRoutineConfirmed
        case routineDeleted
        case deleteDismissHandled
        case logsLoaded([RoutineLog])
        case openLinkedTask(UUID)
        case addLinkedTaskRelationshipKindChanged(RoutineTaskRelationshipKind)
        case openAddLinkedTask
        case editColorChanged(RoutineTaskColor)
        case todoStateChanged(TodoState)
        case pressureChanged(RoutineTaskPressure)
        case thinkingNeededChanged(RoutineTaskThinkingNeeded)
        case importanceChanged(RoutineTaskImportance)
        case urgencyChanged(RoutineTaskUrgency)
        case setBlockedStateConfirmation(Bool)
        case confirmBlockedStateCompletion
        case notificationDisabledWarningTapped
        case notificationStatusLoaded(appEnabled: Bool, systemAuthorized: Bool)
        case onAppear
    }
}
