import Foundation

extension CloudSharingService {
    struct SharedTaskPayload: Codable, Sendable {
        var id: UUID
        var name: String?
        var emoji: String?
        var taskDescription: String?
        var notes: String?
        var link: String?
        var links: [String]?
        var linkItems: [RoutineTaskLink]?
        var deadline: Date?
        var plannedDate: Date?
        var isAllDay: Bool?
        var routineDurationMode: RoutineDurationMode?
        var availabilityStartDate: Date?
        var availabilityEndDate: Date?
        var reminderAt: Date?
        var priority: RoutineTaskPriority
        var importance: RoutineTaskImportance
        var urgency: RoutineTaskUrgency
        var hasExplicitImportance: Bool?
        var hasExplicitUrgency: Bool?
        var pressure: RoutineTaskPressure
        var pressureUpdatedAt: Date?
        var thinkingNeeded: RoutineTaskThinkingNeeded?
        var imageData: Data?
        var voiceNoteData: Data?
        var voiceNoteDurationSeconds: Double?
        var voiceNoteCreatedAt: Date?
        var placeID: UUID?
        var placeIDs: [UUID]?
        var destinationAddress: String?
        var destinationLatitude: Double?
        var destinationLongitude: Double?
        var tags: [String]
        var flags: [String]?
        var goalIDs: [UUID]?
        var eventIDs: [UUID]?
        var relationships: [RoutineTaskRelationship]
        var steps: [RoutineStep]
        var checklistItems: [RoutineChecklistItem]
        var scheduleMode: RoutineScheduleMode
        var interval: Int16
        var recurrenceRule: RoutineRecurrenceRule?
        var recurrenceTimeRangeRole: RoutineTimeRangeRole?
        var lastDone: Date?
        var lastSatisfiedScheduledOccurrenceAt: Date?
        var canceledAt: Date?
        var scheduleAnchor: Date?
        var pausedAt: Date?
        var pauseUntil: Date?
        var snoozedUntil: Date?
        var pinnedAt: Date?
        var taskRankingOrderStorage: String?
        var temporalWeightRuleStorage: String?
        var completedStepCount: Int16
        var sequenceStartedAt: Date?
        var color: RoutineTaskColor
        var createdAt: Date?
        var todoStateRawValue: String?
        var activityStateRawValue: String?
        var ongoingSince: Date?
        var autoAssumeDailyDone: Bool
        var hidesAssumedDoneCalendarBlock: Bool?
        var autoAssumeDoneTimeOfDay: RoutineTimeOfDay?
        var estimatedDurationMinutes: Int?
        var actualDurationMinutes: Int?
        var storyPoints: Int?
        var focusModeEnabled: Bool
        var cadenceEnabled: Bool?
        var autoPauseAfterCompletion: Bool?
        var nudgesEnabled: Bool?
        var comments: [RoutineTaskComment]?
    }
}
